# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TWWeChatMoments' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TWWeChatMoments

  target 'TWWeChatMomentsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TWWeChatMomentsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
